feat.트리
MLifeFam/cs_interview pull request #30
Opened 2021-05-01 05:08 UTC by kouym7979

트리 첫 포스팅입니다.

## 이 풀 리퀘스트는 이러한 내용입니다. (해당내용 괄호 안에 x표시 부탁드립니다.)

- [ ] 버그 개선
- [ ] 오타 수정
- [x] 새로운 내용
- [ ] 기타

#### 설명
트리 첫 포스팅입니다.
부족하거나 궁금한 내용 추가로 알려주시면 조사해서 수정해두겠습니다

2021-05-01 05:20 UTC, Kyun2da requested changes
이미지 주소랑 기여자 이미지 크기 때문에 리뷰한 코드로 사용해주시면 감사하겠습니다.

2021-05-01 05:20 UTC, Kyun2da commented on docs/자료구조/02_트리.md
> +[![img](https://avatars.githubusercontent.com/u/52284829?v=4?s=100)
로컬에서 실행해보니까 기여자 이미지가 너무 큰거 같아요. 아래 코드 복붙해서 사용해주시면 좋을 것 같아요

<td align="center"><a href="https://github.com/kouym7979"><img src="https://avatars.githubusercontent.com/u/52284829?v=4?s=100" width="100px;" alt=""/><br /><sub><b>Youngwoo Kim</b></sub></a><br /><a href="#platform-kouym7979" title="Packaging/porting to new platform">📦</a></td>

2021-05-01 05:20 UTC, Kyun2da commented on docs/자료구조/02_트리.md
> +![tree](https://user-images.githubusercontent.com/52284829/116770298-ade48280-aa7d-11eb-9d76-24f766380ed6.png)
이미지 주소가 다른 것 같습니다. 레포지토리 안에 있는 이미지 주소로 통일 부탁드리겠습니다.

ex) /img/Data-Structure/이미지.png

2021-05-01 05:20 UTC, Kyun2da commented on docs/자료구조/02_트리.md
> +![tree_example](https://user-images.githubusercontent.com/52284829/116771148-120a4500-aa84-11eb-8d28-90c32a3abc77.jpg)
이미지 주소가 다른 것 같습니다. 레포지토리 안에 있는 이미지 주소로 통일 부탁드리겠습니다.

ex) /img/Data-Structure/이미지.png

2021-05-01 05:20 UTC, Kyun2da commented on docs/자료구조/02_트리.md
> +![graph-vs-tree](https://user-images.githubusercontent.com/52284829/116770214-bdaf9700-aa7c-11eb-8582-c0966fd0e184.png)
이미지 주소가 다른 것 같습니다. 레포지토리 안에 있는 이미지 주소로 통일 부탁드리겠습니다.

ex) /img/Data-Structure/이미지.png

2021-05-01 06:25 UTC, kouym7979 commented on docs/자료구조/02_트리.md
> +[![img](https://avatars.githubusercontent.com/u/52284829?v=4?s=100)
오호.. 알겠습니다

2021-05-01 08:44 UTC, Jongminfire approved these changes
기여자 부분만 다음과 같이 변경되면 좋을 것 같습니다~

~~~
<td align="center">
    <a href="https://github.com/kouym7979">
        <img src="https://avatars.githubusercontent.com/u/52284829?v=4?s=100" width="100px;" alt=""/>
        <br />
        <sub>
            <b>Youngwoo Kim</b>
        </sub>
    </a>
    <br />
    <a href="#platform-kouym7979" title="Packaging/porting to new platform">
    📦
    </a>
</td>
~~~

2021-05-01 11:15 UTC, zoolake approved these changes
확인했습니다 !

2021-05-01 13:04 UTC, Kyun2da approved these changes

2021-05-01 13:14 UTC, Kyun2da requested changes

2021-05-01 13:14 UTC, Kyun2da commented on docs/자료구조/02_트리.md
> +[📦](https://github.com/MLifeFam/cs_interview/pull/30#platform-kouym7979)
기여자 부분 아래와 같이 변경 부탁드립니다.

```
<td align="center">
    <a href="https://github.com/kouym7979">
        <img src="https://avatars.githubusercontent.com/u/52284829?v=4?s=100" width="100px;" alt=""/>
        <br />
        <sub>
            <b>Youngwoo Kim</b>
        </sub>
    </a>
    <br />
    <a href="#platform-kouym7979" title="Packaging/porting to new platform">
    📦
    </a>
</td>
```

2021-05-01 13:14 UTC, Kyun2da commented on docs/자료구조/02_트리.md
> +![tree_example](img/Data-Structure/Tree//tree_example.png)
이미지 주소가 첨부된 사진과 주소가 달라 pre deploy 에러가 납니다.
이미지 주소 아래와 같이 일치하도록 변경 부탁드립니다.

```
![tree_example](/img/Data-Structure/Tree/tree_example.jpg)
```

2021-05-02 12:33 UTC, kouym7979 commented on docs/자료구조/02_트리.md
> +![tree_example](img/Data-Structure/Tree//tree_example.png)
넵 img경로앞에 /붙여서 다시 업로드할게요.

2021-05-02 14:04 UTC, Kyun2da approved these changes

2021-05-02 14:08 UTC, Kyun2da requested changes
사진 이미지 경로 바꿔주셔서 감사합니다.

근데.. 사진은 왜삭제하셨나요 이러면 다시 에러가 생깁니다.. ㅠㅠ
사진 3개 다시 넣어서 커밋 부탁드립니다.

2021-05-03 03:07 UTC, Kyun2da approved these changes
굿굿!

2021-05-03 03:08 UTC, merged