Hong eunho
MLifeFam/cs_interview pull request #32
Opened 2021-05-01 15:46 UTC by HongEunho

## 이 풀 리퀘스트는 이러한 내용입니다. (해당내용 괄호 안에 x표시 부탁드립니다.)

- [ ] 버그 개선
- [ ] 오타 수정
- [x] 새로운 내용
- [ ] 기타

#### 설명
06_B-Tree & B+Tree 문서 초기 포스팅

2021-05-02 00:07 UTC, Kyun2da commented
다음 리뷰부터는 오른쪽 상단에 리뷰어 등록좀 부탁드립니다~

2021-05-02 00:08 UTC, Kyun2da commented
05_이진탐색트리가 지워져서 컨플릭트가 난거같네요. 메인에있는거 당겨오시고 한번 푸시 부탁드릴게요

2021-05-02 08:33 UTC, HongEunho commented
넵 확인했습니다~

2021-05-02 09:44 UTC, Kyun2da requested changes
이미지 주소들 다시 원래대로 변경 부탁드립니다.

```
ex) C:\Android\AndroidProject\cs_interview\static\img\Data-Structure\B-Tree\TreeStructure.png
-> /img/Data-Structure/B-Tree/TreeStructure.png
```

2021-05-02 09:44 UTC, Kyun2da commented on docs/자료구조/B-Tree & B+Tree.md
> -![TreeStructure](/img/Data-Structure/B-Tree/TreeStructure.png)
@HongEunho 이미지 주소들 이전에 제대로 하셨는데 왜 바꾸셨나요 ㅠㅠ 다시 원상 복구 부탁드릴게요

2021-05-02 12:25 UTC, kouym7979 approved these changes
잘봤습니다~

2021-05-03 03:44 UTC, Kyun2da approved these changes
굿굿

2021-05-03 04:10 UTC, HelloNaks approved these changes
좋습니다

2021-05-03 04:11 UTC, merged