update: 배열 vs 연결리스트 내용 추가 및 수정
MLifeFam/cs_interview pull request #40
Opened 2021-05-07 11:05 UTC by zoolake

1. 연결리스트 연산 시간복잡도 관련 내용 수정
2. 이중 연결리스트, 원형 연결리스트 내용 추가

## 이 풀 리퀘스트는 이러한 내용입니다. (해당내용 괄호 안에 x표시 부탁드립니다.)

- [ ] 버그 개선
- [ ] 오타 수정
- [ ] 새로운 내용
- [x] 기타

#### 설명

2021-05-07 15:44 UTC, HelloNaks approved these changes

2021-05-08 00:00 UTC, Kyun2da requested changes
배포 오류

2021-05-08 00:00 UTC, Kyun2da commented on docs/자료구조/01_배열 vs 연결리스트.md
> +    ![](/img/Data-Structure/Array_and_LinkedList/doubly_linked_list_2.jpg)
이거 파일확장자를 .JPG로 해주셔야 인식이 될 것 같습니다. 바꿔서 다시 커밋 부탁드립니다 :)

2021-05-08 15:29 UTC, zoolake commented on docs/자료구조/01_배열 vs 연결리스트.md
> +    ![](/img/Data-Structure/Array_and_LinkedList/doubly_linked_list_2.jpg)
해당 원본 이미지 파일확장자는 jpg로 되어있는데, 혹시 어느 부분을 수정해야 하는지 다시 설명부탁드립니다!

2021-05-09 01:42 UTC, Kyun2da commented on docs/자료구조/01_배열 vs 연결리스트.md
> +    ![](/img/Data-Structure/Array_and_LinkedList/doubly_linked_list_2.jpg)
@zoolake 현재 이미지 이름의 확장자가 **대문자** JPG로 되어있어요. 이미지 이름을 소문자로 바꾸시거나 문서쪽 이미지참조 이름을 대문자 JPG로 바꿔주셔야 배포오류가 정상적으로 바뀔듯 합니다.

2021-05-09 04:29 UTC, zoolake commented on docs/자료구조/01_배열 vs 연결리스트.md
> +    ![](/img/Data-Structure/Array_and_LinkedList/doubly_linked_list_2.jpg)
수정했습니다! 감사합니다~

2021-05-09 04:30 UTC, Kyun2da approved these changes

2021-05-09 04:30 UTC, Kyun2da commented
대신 머지합니다!

2021-05-09 04:30 UTC, merged